config/routes.rb
Eieosasco::Application.routes.draw do

  localized do
    resources :registrations
    resources :users
    resources :user_sessions
    resources :activities
    resources :papers
    
    root :to => "home#index"

    match "registration_destroy/:id" =>'registrations#destroy', :as => 'registration_destroy'
    match "paper_destroy/:id" =>'papers#destroy', :as => 'paper_destroy'

    match "registration/completed" =>'registrations#completed', :as => 'registration_completed'
    match "validate_paper_user" =>'papers#validate_paper_user', :as => 'validate_paper_user'
    match "new_paper_user" =>'papers#new', :as => 'new_paper_user'
    match "registration_new" =>'registrations#new', :as => 'registration_new'

    match 'sign_up' => 'users#sign_up', :as => 'sign_up'
    match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
    match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'

    match 'paineis/:id/participantes' => 'activities#participations', :as => 'participations_per_activity'

    match 'search/employees' => 'employees#search', :as => 'employees_search'

    match 'export_data/registrations' => 'registrations#export_data', :as => 'export_data_registrations'
    match 'papers/:id/update_status/:status' => 'papers#update_status', :as => 'update_paper_status'
    match 'dashboard' => 'home#index', :as => 'dashboard'

    match 'registrations/:id/edit_new_data' => 'registrations#edit_new_data', :as => 'edit_new_data'
    match 'registrations/:id/update_new_data' => 'registrations#update_new_data', :as => 'update_new_data'
    match 'sem_circulo' => 'home#without_activity', :as => 'without_activity'
    match 'buscar_certificado' => 'registrations#search_certificate', :as => 'search_certificate'
    match 'baixar_certificado' => 'registrations#download_certificate', :as => 'download_certificate'
    match 'visualizar_trabalhos' => 'papers#approved_papers', :as => 'approved_papers'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @total_registrations = Registration.count
    @total_presencial = Registration.count(:conditions => "participation_type = 0")
    @total_remote = Registration.count(:conditions => "participation_type = 1")
    @total_papers = Paper.count
    @without_participation = Registration.count(:conditions => "id NOT IN (select registration_id from participations)")
    @activities_data = []
    Activity.all.each do |a|
      total_presencial = Participation.find_by_sql("
        SELECT count(*) as total FROM participations p
        INNER JOIN registrations r ON p.registration_id = r.id
        WHERE r.participation_type = 0
        AND p.activity_id = #{a.id}").first.total
      total_remote = Participation.find_by_sql("
        SELECT count(*) as total FROM participations p
        INNER JOIN registrations r ON p.registration_id = r.id
        WHERE r.participation_type = 1
        AND p.activity_id = #{a.id}").first.total
      @activities_data << {:name => a.name, :total_presencial => total_presencial, :total_remote => total_remote}
    end
  end

  def without_activity
    @registrations = Registration.all(:conditions => "id NOT IN (select registration_id from participations)")
  end
  
end

app/views/home/index.html.haml
.white-box-top
.white-box-container
  .content
    .links
      .button_div{:style => 'width: 140px;'}
        = link_to "Inscrições", registrations_path
      .button_div{:style => 'width: 150px;'}
        = link_to "Trabalhos Enviados", papers_path
    %br
    %br
    %br
    .left_panel
      .stats_div
        Total de inscrições
        %span
          = @total_registrations
      .stats_div        
        Presencial
        %span
          = @total_presencial
      .stats_div        
        A distância
        %span
          = @total_remote
    .right_panel

      .stats_div
        Total de trabalhos enviados
        %span
          = @total_papers
    %br
    .dot_border
    %br
    %h2 Detalhamento da participação dos inscritos
    %br
    .stats_div
      Inscritos que ainda não atualizaram o cadastro
      %span
        = link_to @without_participation, without_activity_path
      
    - @activities_data.each do |a|
      .stats_div
        - if a[:name] == "Não participarei no período da manhã"
          %i= "Não participará no período da manhã"
        - else
          %i= a[:name]
        %br
        .second_nivel
          Total de inscritos presencial
          %span
            = a[:total_presencial]
        .second_nivel
          Total de inscritos à distância
          %span
            = a[:total_remote]

  .clearfix

.white-box-bot

app/views/home/without_activity.html.haml
.white-box-top
.white-box-container
  .content{:style => 'font-size:11px;'}
    .button_div{:style => 'width: 60px;'}
      = link_to t('back'), root_path
    .button_div{:style => 'width: 60px; float:right;'}  
      = link_to 'Exportar', registrations_path(:format => :csv)
    %br
    %br
    %br
    = render '/registrations/list', :registrations => @registrations
    
    %br

  .clearfix

.white-box-bot