config/routes.rb
Eieosasco::Application.routes.draw do

  localized do
    resources :registrations
    resources :users
    resources :user_sessions
    resources :activities
    resources :papers
    
    root :to => "home#index"

    match "registration_destroy/:id" =>'registrations#destroy', :as => 'registration_destroy'
    match "paper_destroy/:id" =>'papers#destroy', :as => 'paper_destroy'

    match "registration/completed" =>'registrations#completed', :as => 'registration_completed'
    match "validate_paper_user" =>'papers#validate_paper_user', :as => 'validate_paper_user'
    match "new_paper_user" =>'papers#new', :as => 'new_paper_user'
    match "registration_new" =>'registrations#new', :as => 'registration_new'

    match 'sign_up' => 'users#sign_up', :as => 'sign_up'
    match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
    match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'

    match 'paineis/:id/participantes' => 'activities#participations', :as => 'participations_per_activity'

    match 'search/employees' => 'employees#search', :as => 'employees_search'

    match 'export_data/registrations' => 'registrations#export_data', :as => 'export_data_registrations'
    match 'papers/:id/update_status/:status' => 'papers#update_status', :as => 'update_paper_status'
    match 'dashboard' => 'home#index', :as => 'dashboard'

    match 'registrations/:id/edit_new_data' => 'registrations#edit_new_data', :as => 'edit_new_data'
    match 'registrations/:id/update_new_data' => 'registrations#update_new_data', :as => 'update_new_data'
    match 'sem_circulo' => 'home#without_activity', :as => 'without_activity'
    match 'buscar_certificado' => 'registrations#search_certificate', :as => 'search_certificate'
    match 'baixar_certificado' => 'registrations#download_certificate', :as => 'download_certificate'
    match 'visualizar_trabalhos' => 'papers#approved_papers', :as => 'approved_papers'
  end

end

app/models/paper.rb
class Paper < ActiveRecord::Base
  belongs_to :registration

  has_attached_file :artefact
  validates_presence_of :title, :author, :culture_circle
  validates_attachment_presence :artefact, :message => I18n.t('paper.must_be_set')
  validates_attachment_content_type :artefact,
    :content_type => ['application/msword', 'application/vnd.oasis.opendocument.text', 
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    :message => I18n.t('paper.invalid_content_type')
  validate :resume_max_words
  validate :resume_minimum_words
    
  
  TYPES = [['Relato de Experiência',1],['Apresentação Oral',2]]
  CULTURE_CIRCLES = [['Educação Popular',1], ['Educação Cidadã',2], ['Educação de Adultos',3]]
  APPROVED = 1

  scope :presentation, where(:paper_type => 1)
  scope :paper, where(:paper_type => 2)

  def send_notification
    return nil if self.registration.email.blank?
    Notification.paper_sent(self.id).deliver!
  end
  
  def self.get_types_that_didnt_send(paper_type_ids)
    if paper_type_ids.blank?
      return TYPES
    else
      paper_type_ids.each do |id|
        if id == TYPES.first.last
          return [TYPES.last]
        else
          return [TYPES.first]
        end
      end
    end
  end

  def paper_type_to_s
    TYPES.each do |t|
      return t.first if self.paper_type == t.last
    end
    ''
  end

  def culture_circle_to_s
    CULTURE_CIRCLES.each do |t|
      return t.first if self.culture_circle == t.last
    end
    ''
  end

  def self.to_csv_file
    array = []
    all(:include => [:registration], :order => 'registrations.mode_of_payment').each do |p|
      new_array = Array.new(11)
      new_array[0] = p.registration.name if !p.registration.nil?
      new_array[1] = p.created_at.strftime("%d/%m/%Y") if !p.created_at.nil?
      new_array[2] = p.registration.unit if !p.registration.nil?
      new_array[3] = p.registration.phone if !p.registration.nil?
      new_array[4] = p.registration.mobile if !p.registration.nil?
      new_array[5] = p.registration.email if !p.registration.nil?
      new_array[6] = p.registration.mode_of_payment_to_s if !p.registration.nil?
      new_array[7] = p.title
      new_array[8] = p.paper_type_to_s
      new_array[9] = "http://inscricao.eieosasco.net#{p.artefact.url}"
      new_array[10] = p.activity.name
      new_array[11] = p.registration.city if !p.registration.nil?
      (0..11).each do |i|
        new_array[i] = "  " if new_array[i].blank?
      end
      array << new_array
    end
    array
  end

private 
  
  def resume_max_words
    if !self.resume.blank?
      errors.add(:resume, 'deve ter no máximo 500 palavras') if self.resume.split(' ').size > 500
    end
  end

  def resume_minimum_words
    if !self.resume.blank?
      errors.add(:resume, 'deve ter no mínimo 150 palavras') if self.resume.split(' ').size < 150
    else
      errors.add(:resume, 'deve ter no mínimo 150 palavras') 
    end
  end


end

app/controllers/papers_controller.rb
class PapersController < ApplicationController

  skip_before_filter :require_user, :only=>[:new, :create, :validate_paper_user, :approved_papers]

  layout :set_layout

  def index
    @papers = Paper.all(:include => [:registration])
    respond_to do |format|
      format.html
      format.csv do
        @papers_to_csv = Paper.to_csv_file
        @filename = 'trabalhos.csv'
        @output_encoding = 'UTF-8'
      end
    end 
  end


  def new

  end

  def validate_paper_user
    cpf = params[:cpf]
    cpf = "#{cpf.slice(0..2)}.#{cpf.slice(3..5)}.#{cpf.slice(6..8)}-#{cpf.slice(9..10)}"
    @registration = Registration.find_by_cpf(cpf)
    if @registration.nil?
      @registration = Registration.find_by_cpf(params[:cpf])
    end
    @paper = Paper.new
    respond_to do |format|
    if @registration.nil?
        format.html { redirect_to(new_paper_user_path, :notice => 'O CPF informado não está inscrito no evento, se inscreva antes, para poder enviar o seu trabalho.') }
        format.xml  { render :status => :unprocessable_entity }
    elsif @registration.papers.count == 2
      format.html { redirect_to(new_paper_user_path, :notice => 'Você já enviou o máximo de trabalhos permitido.') }
      format.xml  { render :status => :unprocessable_entity }
    else
        get_new_paper_data
        format.html
        format.xml  { render :xml => @registration }
      end
    end
  end

  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        @paper.send_notification
        format.html { redirect_to(new_paper_user_path, :notice => 'Trabalho salvo com sucesso.') }
        format.xml  { render :xml => @paper, :status => :created, :location => @paper }
      else
        @registration = Registration.find(@paper.registration_id)
        get_new_paper_data
        format.html { render :action => "validate_paper_user" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @paper = Paper.find(params[:id])  
    @registration = @paper.registration
  end

  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to(papers_path, :notice => 'Paper was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @paper = Paper.find(params[:id])
  end

    def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to(papers_path) }
      format.xml  { head :ok }
    end
  end

  def update_status
    ActiveRecord::Base.connection.execute "UPDATE papers set status = #{params[:status]} WHERE id = #{params[:id]}"
    @paper = Paper.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def approved_papers
    @papers = Paper.all(:include => [:registration], :conditions => "status = 1")
  end

protected

  def get_new_paper_data
    @paper_types = Paper.get_types_that_didnt_send(@registration.papers.collect(&:paper_type))
  end

  def set_layout
    if @current_user.nil?
      'unlogged'
    else
      'application'
    end

  end
end

app/views/papers/_form.html.haml
#form
  #paper_form
    = semantic_form_for @paper, :html => { :multipart => true} do |f|
      -if @paper.errors.any?
        #error_explanation
          %ul
            - @paper.errors.full_messages.each do |msg|
              %li= msg
          %br
      .field
        = f.input :title
      .field
        = f.input :author
      .field
        = f.input :coauthor
      .field
        %div{:style => 'width: 400px;'}
          = f.label :resume
          %i{:style => 'float:left; padding-top:6px;'} (O resumo deve ter de 150 a 500 palavras)
        = f.text_area :resume, :cols => '55'
      .field
      = f.input :key_words
      .field
        = f.input :culture_circle, :as => :select, :collection => Paper::CULTURE_CIRCLES, :prompt => t('select')
      .field
        = f.input :artefact, :as => :file, :required => true
      = f.input :registration_id, :value => @registration.id, :as => :hidden
      = f.submit t('send')

app/views/papers/approved_papers.html.haml
:javascript
  $(document).ready(function(){
    var oTable = $('.list').dataTable({
          "iDisplayLength": -1,
          "bAutoWidth": false,
          "bJQueryUI": true,
          "bPaginate": false,
          "bSort": true,
          "bLengthChange": false,
          "bFilter": false,
          "sDom": '<"H"lTfr>t<"F"ip>',
          "aoColumnDefs": [ { "bSortable": false, "aTargets": [4] }],
          "oTableTools": {
             "sSwfPath": "DataTables-1.8.1/media/swf/copy_cvs_xls_pdf.swf"
          },
          'oLanguage': {
            'oPaginate': {
              'sFirst': 'primeira',
              'sLast': 'ultima',
              'sNext': 'próxima',
              'sPrevious': 'anterior'
            },
            'sInfo': 'exibindo de _START_ até _END_ do total de _TOTAL_ registros',
            'sEmptyTable': 'não há registros para exibir',
            'sInfoFiltered': '- filtrando de _MAX_ registros',
            'sInfoPostFix': '',
            'sLengthMenu': 'exibe _MENU_ registros',
            'sProcessing': 'processando',
            'sSearch': 'filtrar',
            'sZeroRecords': 'não há registros para exibir'
          }
        });
  });

#paper_approved
  .content
    - if @papers.count > 0
      %table{:id => 'papers', :class => 'list', :style => "width: 400px"}
        %thead
          %tr
            %th= t('paper.title')
            %th= t('paper.author')
            %th= t('paper.coauthor')
            %th= t('paper.culture_circle')
            %th

            
        %tbody
          - @papers.each do |paper|
            %tr
              %td= paper.title
              %td= paper.author
              %td= paper.coauthor
              %td= paper.culture_circle_to_s
              %td 
                =link_to t('download'), "http://inscricao.paulofreire.org#{paper.artefact.url}"
                
              
        
      %br
    - else
      Não há trabalhos enviados ainda.

app/views/papers/edit.html.haml
.white-box-top
.white-box-container
  .content
    %h1= t('paper.edit')
    %br
    #custom_form
      = render 'form', :button => t('edit')
  .clearfix

.white-box-bot

app/views/papers/index.html.haml
:javascript
  $(document).ready(function(){
    var oTable = $('.list').dataTable({
          "iDisplayLength": -1,
          "bAutoWidth": false,
          "bJQueryUI": true,
          "bSort": true,
          "sDom": '<"H"lTfr>t<"F"ip>',
          "oTableTools": {
             "sSwfPath": "DataTables-1.8.1/media/swf/copy_cvs_xls_pdf.swf"
          },
          "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 5, 6] }],
          'oLanguage': {
            'oPaginate': {
              'sFirst': 'primeira',
              'sLast': 'ultima',
              'sNext': 'próxima',
              'sPrevious': 'anterior'
            },
            'sInfo': 'exibindo de _START_ até _END_ do total de _TOTAL_ registros',
            'sEmptyTable': 'não há registros para exibir',
            'sInfoFiltered': '- filtrando de _MAX_ registros',
            'sInfoPostFix': '',
            'sLengthMenu': 'exibe _MENU_ registros',
            'sProcessing': 'processando',
            'sSearch': 'filtrar',
            'sZeroRecords': 'não há registros para exibir'
          }
        });
  });
.white-box-top
.white-box-container
  .content
    .button_div{:style => 'width: 60px;'}
      = link_to t('back'), root_path

    .button_div{:style => 'width: 60px; float:right;'}  
      = link_to 'Exportar', papers_path(:format => :csv)
    %br
    %br
    %h1= t('paper.list')
    %br
    - if @papers.count > 0
      %table{:id => 'papers', :class => 'list'}
        %thead
          %tr
            %th= t('paper.title')
            %th= t('paper.author')
            %th= t('paper.coauthor')
            %th= t('paper.culture_circle')
            %th= t('paper.created_at')
            %th
            %th
            
        %tbody
          - @papers.each do |paper|
            %tr
              %td{:style => 'width: 100px;'}= paper.title
              %td{:style => 'width: 80px;'}= paper.author
              %td{:style => 'width: 90px; float:left;'}= paper.coauthor
              %td= paper.culture_circle_to_s
              %td= paper.created_at.try(:strftime, "%d/%m/%Y %H:%M")
              %td
                %div{:id => "status_bt_#{paper.id}"}
                  = generate_status_button(paper)
              %td 
                =link_to t('download'), "http://inscricao.paulofreire.org#{paper.artefact.url}"
                %br
                =link_to t('edit'), edit_paper_path(:id => paper.id)
                %br
                =link_to t('destroy'), paper_destroy_path(:id => paper.id)
              
        
      %br
    - else
      Não há trabalhos enviados ainda.

.white-box-bot

app/views/papers/new.html.haml
#whitebox_default 
  %p
    %b= notice
  %br

  - form_tag validate_paper_user_path, :method => :put, :id => 'send_work' do
    = label_tag :cpf, 'Informe o seu CPF:', :style => 'width: 150px;'
    = text_field_tag :cpf, nil, :class => "exempting_registration"
    = submit_tag 'Próxima etapa'
  %br
.clearfix

app/views/papers/show.html.haml
%p#notice= notice

%p
  %b Atividade:
  = @paper.activity.name
%p
  %b Usuário:
  = @paper.registration.name
%p
  %b Tipo do Trabalho:
  = @paper.paper_type
%p
  %b Título:
  = @paper.title
%p
  %b Arquivo:
  = @paper.file
%p
  %b Observações:
  = @paper.observation

app/views/papers/update_status.js.haml
$("#status_bt_#{@paper.id}").html("#{escape_javascript(generate_status_button(@paper))}")

app/views/papers/validate_paper_user.html.haml
#custom_form
  = render 'form', :button => t('send')

  .clearfix