config/routes.rb
Eieosasco::Application.routes.draw do

  localized do
    resources :registrations
    resources :users
    resources :user_sessions
    resources :activities
    resources :papers
    
    root :to => "home#index"

    match "registration_destroy/:id" =>'registrations#destroy', :as => 'registration_destroy'
    match "paper_destroy/:id" =>'papers#destroy', :as => 'paper_destroy'

    match "registration/completed" =>'registrations#completed', :as => 'registration_completed'
    match "validate_paper_user" =>'papers#validate_paper_user', :as => 'validate_paper_user'
    match "new_paper_user" =>'papers#new', :as => 'new_paper_user'
    match "registration_new" =>'registrations#new', :as => 'registration_new'

    match 'sign_up' => 'users#sign_up', :as => 'sign_up'
    match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
    match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'

    match 'paineis/:id/participantes' => 'activities#participations', :as => 'participations_per_activity'

    match 'search/employees' => 'employees#search', :as => 'employees_search'

    match 'export_data/registrations' => 'registrations#export_data', :as => 'export_data_registrations'
    match 'papers/:id/update_status/:status' => 'papers#update_status', :as => 'update_paper_status'
    match 'dashboard' => 'home#index', :as => 'dashboard'

    match 'registrations/:id/edit_new_data' => 'registrations#edit_new_data', :as => 'edit_new_data'
    match 'registrations/:id/update_new_data' => 'registrations#update_new_data', :as => 'update_new_data'
    match 'sem_circulo' => 'home#without_activity', :as => 'without_activity'
    match 'buscar_certificado' => 'registrations#search_certificate', :as => 'search_certificate'
    match 'baixar_certificado' => 'registrations#download_certificate', :as => 'download_certificate'
    match 'visualizar_trabalhos' => 'papers#approved_papers', :as => 'approved_papers'
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :participations
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.xml
  def index
    @activities = Activity.all(:order => "(name + 0) ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.xml
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.xml
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.xml
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to(activities_path, :notice => 'Activity was successfully created.') }
        format.xml  { render :xml => @activity, :status => :created, :location => @activity }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.xml
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to(activities_path, :notice => 'Activity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.xml
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to(activities_url) }
      format.xml  { head :ok }
    end
  end


end

app/views/activities/_form.html.haml
#form
  = semantic_form_for @activity do |f|
    -if @activity.errors.any?
      #error_explanation
        %ul
          - @activity.errors.full_messages.each do |msg|
            %li= msg

    %br
    .field
      = f.input :name
    .field
      = f.input :lotation
    .actions
      = f.submit t('save')

app/views/activities/edit.html.haml
.white-box-top
.white-box-container
  .content
    .button_div{:style => 'width: 60px;'}
      = link_to t('back'), activities_path
    %br
    %br
    %br
    %h1= t('activity.edit')

    = render 'form'

  .clearfix

.white-box-bot

app/views/activities/index.html.haml
.white-box-top
.white-box-container
  .content
    .button_div{:style => 'width: 60px;'}
      = link_to t('back'), root_path
    .button_div{:style => 'width: 150px; float: right;'}
      = link_to t('activity.new'), new_activity_path
    %br
    %br
    %br
    %h1= t('activity.list')
    %br
    %table
      %tr
        %th= t('activity.name')        
        %th= t('activity.lotation') 

      - @activities.each do |activity|
        %tr
          %td= activity.name
          %td= activity.lotation


    %br

app/views/activities/new.html.haml
.white-box-top
.white-box-container
  .content
    .button_div{:style => 'width: 60px;'}
      = link_to t('back'), activities_path
    %br
    %br
    %br
    %h1= t('activity.new')

    = render 'form'
  
  .clearfix

.white-box-bot

app/views/activities/participations.html.haml
.white-box-top
.white-box-container
  .content{:style => 'font-size:11px;'}
    .button_div{:style => 'width: 60px;'}
      = link_to t('back'), root_path
    %br
    %br
    %br
    %h1= "Participantes do paínel <i>#{@activity.name}</i>".html_safe
    %br
    = render '/registrations/list', :registrations => @participations
  .clearfix

.white-box-bot

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @activity.name
%p
  %b Description:
  = @activity.description
%p
  %b Start at:
  = @activity.start_at
%p
  %b End at:
  = @activity.end_at
%p
  %b Total places:
  = @activity.total_places

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path